version: "3.8"

services:
  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001

  backend:
    build:
      context: .
      target: backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/jobify?schema=public
      - PORT=3001
      - NODE_ENV=development
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    depends_on:
      - database

  database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jobify
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
